### ISSUE TITLE
Issue when bundling with webpack

### ISSUE THREAD

**Issue by gottipatibalu** [typestack/microframework#9]
I am having issues when trying to bundle with webpack

**Warning when bundling with webpack**

WARNING in ./node_modules/app-root-path/lib/app-root-path.js 14:10-56
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/app-root-path/index.js
 @ ./node_modules/microframework/Microframework.js
 @ ./node_modules/microframework/index.js
 @ ./app.ts

WARNING in ./node_modules/microframework/Microframework.js
Module not found: Error: Can't resolve 'ascii-art' in '/Users/bgottip/Desktop/template/nodeproj/node_modules/microframework'
 @ ./node_modules/microframework/Microframework.js
 @ ./node_modules/microframework/index.js
 @ ./app.ts

**Error when running the file using node**

node dist/server.js 
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:1265:5)
    at resolve (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:615:22)
    at module.exports (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:497:20)
    at Object.module.exports (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:485:18)
    at __webpack_require__ (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:20:30)
    at Microframework.config (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:204:26)
    at Object.bootstrapMicroframework (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:163:10)
    at Object.defineProperty.value (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:115:18)
    at __webpack_require__ (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:20:30)

I am using very basic code

**server.ts**
import { bootstrapMicroframework } from 'microframework';
BootstrapMicroframework({
  config: {
    showBootstrapTime: true,
    bootstrapTimeout: 10
  }
});
console.log('done');

any pointers will be greatly appreciated.

**Comment by baoyule-js** [comment]
the same ,have you solved this ?

**Comment by NoNameProvided** [comment]
Closing as this project is being deprecated. 

If you have been using this project as webserver please use [typetack/routing-controllers](https://github.com/typestack/routing-controllers) instead.
